// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../resource';
import * as ImagesAPI from './images';
import * as EditsAPI from './edits';
import * as GenerationsAPI from './generations';
import * as VariationsAPI from './variations';

export class Images extends APIResource {
  generations: GenerationsAPI.Generations = new GenerationsAPI.Generations(this._client);
  edits: EditsAPI.Edits = new EditsAPI.Edits(this._client);
  variations: VariationsAPI.Variations = new VariationsAPI.Variations(this._client);
}

export interface ImageResponse {
  created: number;

  data: Array<ImageResponse.Data>;
}

export namespace ImageResponse {
  /**
   * Represents the url or the content of an image generated by the OpenAI API.
   */
  export interface Data {
    /**
     * The base64-encoded JSON of the generated image, if `response_format` is
     * `b64_json`.
     */
    b64_json?: string;

    /**
     * The prompt that was used to generate the image, if there was any revision to the
     * prompt.
     */
    revised_prompt?: string;

    /**
     * The URL of the generated image, if `response_format` is `url` (default).
     */
    url?: string;
  }
}

export namespace Images {
  export import ImageResponse = ImagesAPI.ImageResponse;
  export import Generations = GenerationsAPI.Generations;
  export import GenerationCreateParams = GenerationsAPI.GenerationCreateParams;
  export import Edits = EditsAPI.Edits;
  export import EditCreateParams = EditsAPI.EditCreateParams;
  export import Variations = VariationsAPI.Variations;
  export import VariationCreateParams = VariationsAPI.VariationCreateParams;
}
